server.port=8088
management.endpoints.web.exposure.include=*

# Zeebe
######################
camunda.client.mode=self-managed
#camunda.client.tenant-id=default
#camunda.client.auth.client-id=
#camunda.client.auth.client-secret=
#camunda.client.auth.token-url=http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
#camunda.client.zeebe.audience=zeebe-api
#camunda.client.zeebe.scope=# optional
camunda.client.zeebe.enabled=true
camunda.client.zeebe.grpc-address=http://127.0.0.1:26500
#camunda.client.zeebe.rest-address=
camunda.client.zeebe.execution-threads=100
camunda.client.zeebe.prefer-rest-over-grpc=false
camunda.client.zeebe.defaults.max-jobs-active=2000
camunda.client.zeebe.defaults.stream-enabled=true
camunda.client.zeebe.request-timeout=PT60S

# Main benchmark configurations
######################
benchmark.startProcesses=true
benchmark.startPiPerSecond=100
benchmark.taskCompletionDelay=200
benchmark.bpmnProcessId=PerformanceWorkflow
# Set this to false if you only want to start processes but don't want any workers
benchmark.startWorkers=true
benchmark.jobType=benchmark-task
# Create multiple workers to respond to multiple job types
# By default, only one worker is created and will listen for job type defined above.
# If the value is set to `2`, for example, 2 workers are created: `benchmark-task-1` and `benchmark-task-2`
benchmark.multipleJobTypes=0
# 5 minutes warmup:  5*60*1000
benchmark.warmupPhaseDurationMillis=6000
# can be "none" or "backpressure" or "jobRatio"
benchmark.startRateAdjustmentStrategy=backpressure
benchmark.payloadPath=classpath:bpmn/typical_payload.json
benchmark.autoDeployProcess=false
#benchmark.bpmnResource=classpath:bpmn/complex_decision.dmn;classpath:bpmn/simple_dmn_process.bpmn
benchmark.bpmnResource=classpath:bpmn/PerformanceWorkflow.bpmn
#benchmark.starterId=benchmarkStarter1

benchmark.maxBackpressurePercentage=10.0
benchmark.startPiReduceFactor=0.1
benchmark.startPiIncreaseFactor=0

# BPMN Message Scenario
########################
#benchmark.bpmnResource=classpath:bpmn/msg_process.bpmn
#benchmark.messageScenario=classpath:bpmn/sample-msg-scenario.json
#benchmark.messagesTtl=60
#benchmark.messagesScenariosPerSecond=10
#benchmark.delayBetweenMessages=10000
#benchmark.messagesLoadDuration=1000

######################

async.corePoolSize=5
async.maxPoolSize=100
async.queueCapacity=1000

scheduler.poolSize=60

# when 0, use the default Exponential Backoff Supplier. Otherwise, specify fixed number of millis backoff.
benchmark.fixedBackOffDelay=0

logging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
logging.level.io.camunda.zeebe.client=DEBUG
logging.level.io.camunda.zeebe.spring.client=DEBUG
logging.level.i.c.z.client.impl.oauth.OAuthCredentialsProviderBuilder=DEBUG
